services:
  - type: web
    name: news-youtube-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    region: oregon
    plan: free
